#!/bin/sh

echo stop container...
docker stop reports-container
echo remove service from docker...
docker rm reports-container
echo remove image ...
docker image rm reports-web-app
echo generate local image from dockerfile...
docker build --pull -t reports-web-app  -f Dockerfile.LOCAL .
echo run image into local server...
docker run --name reports-container -d -p 8080:80 reports-web-app
